version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # AMQP protocol
      - "15672:15672"  # Management UI
      - "1883:1883"    # MQTT protocol
    volumes:
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins # Enable plugins
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    restart: always